- project:
    check:
      jobs:
        - "noop"
    gate:
      jobs:
        - "noop"
    release:
      jobs:
        - "upload-pypi-sesheta"
    kebechet-auto-gate:
      jobs:
        - "noop"
