---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trigger-integration
  annotations:
    thoth-station.ninja/template-version: 0.7.0
  labels:
    app: thoth
    component: trigger-integration
spec:
  templates:
    - name: trigger-integration
      inputs:
        parameters:
          - name: "THOTH_WORKFLOW_NAME"
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_ADVISER_METADATA"
      container:
        name: trigger-integration
        image: workflow-helpers
        env:
          - name: THOTH_WORKFLOW_TASK
            value: "trigger_integration"
          - name: APP_SCRIPT
            value: "app.sh"
          - name: THOTH_WORKFLOW_NAME
            value: "{{inputs.parameters.WORKFLOW_NAME}}"
          - name: THOTH_DOCUMENT_ID
            value: "{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: THOTH_ADVISER_METADATA
            value: "{{inputs.parameters.THOTH_ADVISER_METADATA}}"
          - name: "THOTH_WEBHOOK_CALLBACK_URL"
            value: "http://qeb-hwt-aicoe-prod-bots.cloud.paas.psi.redhat.com"
          - name: THOTH_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_SECRET
                name: qeb-hwt-github-app
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
      outputs:
        parameters:
          - name: origin
            valueFrom:
              path: /mnt/workdir/origin
              default: ""
          - name: source_type
            valueFrom:
              path: /mnt/workdir/source_type
              default: ""
